logging:
  level:
    org.springframework.security: INFO
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:    
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current
      
spring:
  rabbitmq:
    host: rabbitmq